<script lang="ts">
  import type { PageServerData } from "./$types"

  let { data }: { data: PageServerData } = $props()

  const kindMark: Record<string, string> = {
    scan: "◇",
    pitch: "▷",
    reply: "◂",
    meeting: "◆",
    sweep: "↻",
    gate: "▮",
    won: "★",
    render: "◹",
    system: "·",
  }

  // Chrome defers autoplay for offscreen videos; nudge ambient loops when
  // they scroll into view (muted, so play() is always permitted).
  function playWhenVisible(node: HTMLVideoElement) {
    const io = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && node.paused) node.play().catch(() => {})
      },
      { threshold: 0.1 },
    )
    io.observe(node)
    return { destroy: () => io.disconnect() }
  }
</script>

<svelte:head>
  <title>{data.client.name} — Monthly Report — {data.monthLabel}</title>
  <meta name="description" content="Monthly performance report for {data.client.name}, generated by Today OS." />
</svelte:head>

<div class="report-sheet bg-base-100 text-base-content min-h-screen">
  <div class="mx-auto max-w-3xl px-4 py-8 sm:px-8 sm:py-12 print:max-w-none print:px-0 print:py-6">
    {#if data.client.isSample}
      <p class="hud text-warning mb-4">SAMPLE REPORT — "{data.client.slug}" not found, showing example data</p>
    {/if}

    <header class="mb-8 border-b pb-6" style="border-color: var(--color-line)">
      <p class="hud text-base-content/50">MONTHLY REPORT · {data.monthLabel.toUpperCase()}</p>
      <h1 class="statement mt-2 text-4xl sm:text-5xl">{data.client.name}</h1>
      <p class="text-base-content/60 mt-2 text-sm">{data.client.city} · {data.client.vertical}</p>
    </header>

    <!-- Summary tiles -->
    <section
      class="grid grid-cols-2 gap-px border sm:grid-cols-3"
      style="border-color: var(--color-line); background: var(--color-line)"
      aria-label="Monthly summary"
    >
      <div class="bg-base-100 p-4">
        <p class="hud text-base-content/50">Ad spend</p>
        <p class="statement mt-2 text-2xl sm:text-3xl">{data.spend}</p>
      </div>
      <div class="bg-base-100 p-4">
        <p class="hud text-base-content/50">Conversions</p>
        <p class="statement mt-2 text-2xl sm:text-3xl">{data.conversions}</p>
      </div>
      <div class="bg-base-100 col-span-2 p-4 sm:col-span-1">
        <p class="hud text-base-content/50">Cost / conversion</p>
        <p class="statement mt-2 text-2xl sm:text-3xl">{data.cpa}</p>
      </div>
    </section>

    <!-- Waste recovered -->
    <section class="mt-6 border p-6 sm:p-8 print:break-inside-avoid" style="border-color: var(--color-line)">
      <p class="hud text-base-content/50">WASTE RECOVERED · THIS MONTH</p>
      <p class="statement text-success mt-3 text-5xl sm:text-6xl">{data.wasteRecovered.value}</p>
      <p class="text-base-content/50 mt-3 text-sm">
        {data.wasteRecovered.source === "store"
          ? "attributed share of waste recovered across accounts under management"
          : "sample figure — illustrative only"}
      </p>
    </section>

    <!-- Actions taken -->
    <section class="mt-6 border print:break-inside-avoid" style="border-color: var(--color-line)">
      <div class="hud border-b px-4 py-2.5" style="border-color: var(--color-line)">ACTIONS TAKEN THIS MONTH</div>
      <ul class="divide-y" style="border-color: var(--color-line)">
        {#each data.actionsTaken as a (a.id)}
          <li class="flex gap-3 px-4 py-2.5">
            <span class="text-primary/70 mt-0.5 shrink-0 font-mono text-xs">{kindMark[a.kind] ?? "·"}</span>
            <p class="text-[13px] leading-snug text-base-content/80">{a.text}</p>
          </li>
        {/each}
      </ul>
    </section>

    <!-- Creative refreshed -->
    <section class="mt-6 print:break-inside-avoid">
      <p class="hud text-base-content/50 mb-2">CREATIVE REFRESHED THIS MONTH</p>
      <div class="grid grid-cols-1 gap-3 sm:grid-cols-3">
        {#each data.creatives as c (c.id)}
          <div class="border print:hidden" style="border-color: var(--color-line)">
            <video
              class="ambient-video aspect-video block w-full object-cover"
              use:playWhenVisible
              src={c.src}
              autoplay
              muted
              loop
              playsinline
              aria-hidden="true"
            ></video>
            <p class="hud text-base-content/45 px-2 py-1.5">{c.label}</p>
          </div>
        {/each}
      </div>
      <ul class="hidden print:block">
        {#each data.creatives as c (c.id)}
          <li class="text-sm">— {c.label}</li>
        {/each}
      </ul>
    </section>

    <!-- Next month's plan -->
    <section class="mt-6 border p-4 sm:p-6 print:break-inside-avoid" style="border-color: var(--color-line)">
      <p class="hud text-base-content/50">NEXT MONTH'S PLAN</p>
      <ul class="mt-3 flex flex-col gap-2">
        {#each data.nextMonthPlan as item, i (i)}
          <li class="text-base-content/80 flex gap-2 text-sm">
            <span class="text-primary/60">→</span>
            <span>{item}</span>
          </li>
        {/each}
      </ul>
    </section>

    <footer class="hud text-base-content/30 mt-8 border-t pt-4" style="border-color: var(--color-line)">
      GENERATED BY TODAY OS · <a href="/os" class="hover:text-base-content">/os</a>
    </footer>
  </div>
</div>

<style>
  /* Print exception: paper wastes ink on a near-black theme, so the printed
     copy of this page overrides the dark Instrument tokens to a plain
     light/dark pair, scoped to this sheet only. Everything downstream still
     reads through the same --color-* variables (bg-base-100, text-base-content,
     border-color: var(--color-line), …) — only the values change for print. */
  @media print {
    .report-sheet {
      --color-base-100: #ffffff;
      --color-base-content: #111111;
      --color-line: #cccccc;
      --color-primary: #111111;
      --color-success: #111111;
      --color-warning: #111111;
    }
  }
  @page {
    margin: 0.75in;
  }
</style>
